using YiJingLibrary.Core;

namespace YiJingLibrary.Test;

public class EarthlyBranchesAdditionalTest
{
    [Fact]
    public void EarthlyBranchClashing_RelationshipsAreCorrect()
    {
        // Zi clashes with Wu
        Assert.True(EarthlyBranch.Zi.IsClashing(EarthlyBranch.Wu));
        Assert.True(EarthlyBranch.Wu.IsClashing(EarthlyBranch.Zi));
        
        // Chou clashes with Wei
        Assert.True(EarthlyBranch.Chou.IsClashing(EarthlyBranch.Wei));
        Assert.True(EarthlyBranch.Wei.IsClashing(EarthlyBranch.Chou));
        
        // Yin clashes with Shen
        Assert.True(EarthlyBranch.Yin.IsClashing(EarthlyBranch.Shen));
        Assert.True(EarthlyBranch.Shen.IsClashing(EarthlyBranch.Yin));
        
        // Mao clashes with You
        Assert.True(EarthlyBranch.Mao.IsClashing(EarthlyBranch.You));
        Assert.True(EarthlyBranch.You.IsClashing(EarthlyBranch.Mao));
        
        // Chen clashes with Xu
        Assert.True(EarthlyBranch.Chen.IsClashing(EarthlyBranch.Xu));
        Assert.True(EarthlyBranch.Xu.IsClashing(EarthlyBranch.Chen));
        
        // Si clashes with Hai
        Assert.True(EarthlyBranch.Si.IsClashing(EarthlyBranch.Hai));
        Assert.True(EarthlyBranch.Hai.IsClashing(EarthlyBranch.Si));
    }

    [Fact]
    public void EarthlyBranchCombining_RelationshipsAreCorrect()
    {
        // Zi combines with Chou
        Assert.True(EarthlyBranch.Zi.IsCombining(EarthlyBranch.Chou));
        Assert.True(EarthlyBranch.Chou.IsCombining(EarthlyBranch.Zi));
        
        // Yin combines with Hai
        Assert.True(EarthlyBranch.Yin.IsCombining(EarthlyBranch.Hai));
        Assert.True(EarthlyBranch.Hai.IsCombining(EarthlyBranch.Yin));
        
        // Mao combines with Xu
        Assert.True(EarthlyBranch.Mao.IsCombining(EarthlyBranch.Xu));
        Assert.True(EarthlyBranch.Xu.IsCombining(EarthlyBranch.Mao));
        
        // Chen combines with You
        Assert.True(EarthlyBranch.Chen.IsCombining(EarthlyBranch.You));
        Assert.True(EarthlyBranch.You.IsCombining(EarthlyBranch.Chen));
        
        // Si combines with Shen
        Assert.True(EarthlyBranch.Si.IsCombining(EarthlyBranch.Shen));
        Assert.True(EarthlyBranch.Shen.IsCombining(EarthlyBranch.Si));
        
        // Wu combines with Wei
        Assert.True(EarthlyBranch.Wu.IsCombining(EarthlyBranch.Wei));
        Assert.True(EarthlyBranch.Wei.IsCombining(EarthlyBranch.Wu));
    }

    [Fact]
    public void EarthlyBranchEmptyBranches_CalculatesCorrectly()
    {
        // Test a few examples to ensure EmptyBranches calculation works
        var jiaZi = new StemBranch(HeavenlyStem.Jia, EarthlyBranch.Zi);
        var emptyBranches = jiaZi.EmptyBranches;
        
        Assert.NotNull(emptyBranches);
        Assert.Equal(2, emptyBranches.Length);
        // JiaZi's empty branches should be Xu and Hai
        Assert.Contains(EarthlyBranch.Xu, emptyBranches);
        Assert.Contains(EarthlyBranch.Hai, emptyBranches);
    }

    [Fact]
    public void EarthlyBranchGeneratesBy_RelationshipsAreCorrect()
    {
        // Water is generated by Metal
        Assert.True(EarthlyBranch.Hai.GeneratesBy(EarthlyBranch.Shen));
        Assert.True(EarthlyBranch.Hai.GeneratesBy(EarthlyBranch.You));
        Assert.True(EarthlyBranch.Zi.GeneratesBy(EarthlyBranch.Shen));
        Assert.True(EarthlyBranch.Zi.GeneratesBy(EarthlyBranch.You));
        
        // Wood is generated by Water
        Assert.True(EarthlyBranch.Yin.GeneratesBy(EarthlyBranch.Zi));
        Assert.True(EarthlyBranch.Yin.GeneratesBy(EarthlyBranch.Hai));
        Assert.True(EarthlyBranch.Mao.GeneratesBy(EarthlyBranch.Zi));
        Assert.True(EarthlyBranch.Mao.GeneratesBy(EarthlyBranch.Hai));
        
        // Fire is generated by Wood
        Assert.True(EarthlyBranch.Si.GeneratesBy(EarthlyBranch.Yin));
        Assert.True(EarthlyBranch.Si.GeneratesBy(EarthlyBranch.Mao));
        Assert.True(EarthlyBranch.Wu.GeneratesBy(EarthlyBranch.Yin));
        Assert.True(EarthlyBranch.Wu.GeneratesBy(EarthlyBranch.Mao));
        
        // Earth is generated by Fire
        Assert.True(EarthlyBranch.Chen.GeneratesBy(EarthlyBranch.Si));
        Assert.True(EarthlyBranch.Chen.GeneratesBy(EarthlyBranch.Wu));
        Assert.True(EarthlyBranch.Xu.GeneratesBy(EarthlyBranch.Si));
        Assert.True(EarthlyBranch.Xu.GeneratesBy(EarthlyBranch.Wu));
        Assert.True(EarthlyBranch.Chou.GeneratesBy(EarthlyBranch.Si));
        Assert.True(EarthlyBranch.Chou.GeneratesBy(EarthlyBranch.Wu));
        Assert.True(EarthlyBranch.Wei.GeneratesBy(EarthlyBranch.Si));
        Assert.True(EarthlyBranch.Wei.GeneratesBy(EarthlyBranch.Wu));
        
        // Metal is generated by Earth
        Assert.True(EarthlyBranch.Shen.GeneratesBy(EarthlyBranch.Chen));
        Assert.True(EarthlyBranch.Shen.GeneratesBy(EarthlyBranch.Xu));
        Assert.True(EarthlyBranch.Shen.GeneratesBy(EarthlyBranch.Chou));
        Assert.True(EarthlyBranch.Shen.GeneratesBy(EarthlyBranch.Wei));
        Assert.True(EarthlyBranch.You.GeneratesBy(EarthlyBranch.Chen));
        Assert.True(EarthlyBranch.You.GeneratesBy(EarthlyBranch.Xu));
        Assert.True(EarthlyBranch.You.GeneratesBy(EarthlyBranch.Chou));
        Assert.True(EarthlyBranch.You.GeneratesBy(EarthlyBranch.Wei));
    }

    [Fact]
    public void EarthlyBranchRestrainsBy_RelationshipsAreCorrect()
    {
        // Water is restrained by Earth
        Assert.True(EarthlyBranch.Zi.RestrainsBy(EarthlyBranch.Chen));
        Assert.True(EarthlyBranch.Zi.RestrainsBy(EarthlyBranch.Xu));
        Assert.True(EarthlyBranch.Zi.RestrainsBy(EarthlyBranch.Chou));
        Assert.True(EarthlyBranch.Zi.RestrainsBy(EarthlyBranch.Wei));
        Assert.True(EarthlyBranch.Hai.RestrainsBy(EarthlyBranch.Chen));
        Assert.True(EarthlyBranch.Hai.RestrainsBy(EarthlyBranch.Xu));
        Assert.True(EarthlyBranch.Hai.RestrainsBy(EarthlyBranch.Chou));
        Assert.True(EarthlyBranch.Hai.RestrainsBy(EarthlyBranch.Wei));
        
        // Wood is restrained by Metal
        Assert.True(EarthlyBranch.Yin.RestrainsBy(EarthlyBranch.Shen));
        Assert.True(EarthlyBranch.Yin.RestrainsBy(EarthlyBranch.You));
        Assert.True(EarthlyBranch.Mao.RestrainsBy(EarthlyBranch.Shen));
        Assert.True(EarthlyBranch.Mao.RestrainsBy(EarthlyBranch.You));
        
        // Fire is restrained by Water
        Assert.True(EarthlyBranch.Si.RestrainsBy(EarthlyBranch.Zi));
        Assert.True(EarthlyBranch.Si.RestrainsBy(EarthlyBranch.Hai));
        Assert.True(EarthlyBranch.Wu.RestrainsBy(EarthlyBranch.Zi));
        Assert.True(EarthlyBranch.Wu.RestrainsBy(EarthlyBranch.Hai));
        
        // Earth is restrained by Wood
        Assert.True(EarthlyBranch.Chen.RestrainsBy(EarthlyBranch.Yin));
        Assert.True(EarthlyBranch.Chen.RestrainsBy(EarthlyBranch.Mao));
        Assert.True(EarthlyBranch.Xu.RestrainsBy(EarthlyBranch.Yin));
        Assert.True(EarthlyBranch.Xu.RestrainsBy(EarthlyBranch.Mao));
        Assert.True(EarthlyBranch.Chou.RestrainsBy(EarthlyBranch.Yin));
        Assert.True(EarthlyBranch.Chou.RestrainsBy(EarthlyBranch.Mao));
        Assert.True(EarthlyBranch.Wei.RestrainsBy(EarthlyBranch.Yin));
        Assert.True(EarthlyBranch.Wei.RestrainsBy(EarthlyBranch.Mao));
        
        // Metal is restrained by Fire
        Assert.True(EarthlyBranch.Shen.RestrainsBy(EarthlyBranch.Si));
        Assert.True(EarthlyBranch.Shen.RestrainsBy(EarthlyBranch.Wu));
        Assert.True(EarthlyBranch.You.RestrainsBy(EarthlyBranch.Si));
        Assert.True(EarthlyBranch.You.RestrainsBy(EarthlyBranch.Wu));
    }
}